#!/usr/bin/env bash

ignore_dirs=(
    $HOME/personal
    $HOME/Downloads
    $HOME
    $HOME/Throne
)

for dir in "${ignore_dirs[@]}"; do
    if [[ "$(pwd)" == $dir ]]; then
        clear
        return
    fi
done

tmux neww -dn scratch
nvim .
clear
