#!/usr/bin/env bash

set -e

dry_run="0"
force="0"

SCRIPT_DIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "XDG_CONFIG_HOME is not set"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

while [[ $# -gt 0 ]]; do
    echo "ARG: $1"
    if [[ $1 == "--dry" ]]; then
        dry_run="1"
        echo "dry run: $dry_run"
    elif [[ $1 == "--force" ]]; then
        force="1"
        echo "force: $force"
    fi
    shift
done

log(){
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

create_symlink() {
    log "linking: $1 to $2"
    if [[ -L $2 ]]; then
        log "   $2 already symlinked"
        return
    fi

    if [[ -e $2 ]]; then
        if [[ $force == "0" ]]; then
            log "   file exists: $2. Use --force to overwrite"
            exit 1
        else
            log "   overwriting: $2"
            log "   rm -r $2"
            if [[ $dry_run == "0" ]]; then
                rm -r $2
            fi
        fi
    fi

    log "   ln -s $1 $2"
    if [[ $dry_run == "0" ]]; then
        ln -s $1 $2
    fi
}

link_subdirs() {
    subdirs=`find $1 -mindepth 1 -maxdepth 1 -type d`
    for d in $subdirs; do
        dest="$2/$(basename $d)"

        if [[ $dry_run == "0" ]]; then
            create_symlink $d $dest
        fi
    done
}

link_subdirs $SCRIPT_DIR/.config $XDG_CONFIG_HOME
link_subdirs $SCRIPT_DIR/.local $HOME/.local
create_symlink $SCRIPT_DIR/qmk $HOME/qmk_firmware/keyboards/crkbd/keymaps/Roddyck
create_symlink $SCRIPT_DIR/.zshenv $HOME/.zshenv
