#!/usr/bin/env bash
dry_run="0"
grep=""

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "XDG_CONFIG_HOME is not set"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z $DEV_ENV ]; then
    echo "enviroment variable DEV_ENV needs to be present"
    exit 1
fi

while [[ $# -gt 0 ]]; do
    echo "ARG: $1"
    if [[ $1 == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log(){
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"
log "grep: $grep"

update_files() {
    log "copying over files from: $1"

    pushd $1 &> /dev/null
    configs=`find . -mindepth 1 -maxdepth 1 -type d`
    for c in $configs; do
        if basename $c | grep -vq "$grep"; then
            log "grep $grep filtered out $c"
            continue
        fi
        directory=${2%/}/${c#./}
        log "   removing: rm -rf $directory"

        if [[ $dry_run == "0" ]]; then
            rm -rf $directory
        fi

        log "   copying env: cp $c $2"
        if [[ $dry_run == "0" ]]; then
            cp -r $c $2
        fi
    done
    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

copy_keyboard() {
    log "copying keyboard: $1 to $2"
    pushd $2 &> /dev/null
    target_files=`find . -mindepth 1 -maxdepth 1 -type f`
    for f in $target_files; do
        target_filepath=${2%/}/${f#./}
        log "   removing: $target_filepath"
        if [[ $dry_run == "0" ]]; then
            rm $target_filepath
        fi
    done
    popd &> /dev/null
    pushd $1 &> /dev/null
    source_files=`find . -mindepth 1 -maxdepth 1 -type f`
    for f in $source_files; do
        source_filepath=${1%/}/${f#./}
        if [[ $(basename $source_filepath) == "README.md" || $(basename $source_filepath) == ".git" || $(basename $source_filepath) == "compile_commands.json" || $(basename $source_filepath) == ".gitignore" ]]; then
            continue
        fi
        log "   copying: $source_filepath"
        if [[ $dry_run == "0" ]]; then
            cp $source_filepath $2
        fi
    done
}

if [[ $grep != "qmk" ]]; then
    update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
    update_files $DEV_ENV/env/.local $HOME/.local

    copy $DEV_ENV/env/.zshenv $HOME/.zshenv
fi


if [[ $grep == "qmk" ]]; then
    copy_keyboard $DEV_ENV/qmk $HOME/qmk_firmware/keyboards/crkbd/keymaps/Roddyck
fi

if [[ $dry_run == "0" ]]; then
    hyprctl reload
fi
