version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "python"
    style = "plain"
    background = "transparent"
    foreground = "white"
    template = '{{ if .Venv }}({{ .Venv }}) {{ end }}'

  [blocks.segments.properties]
    display_mode = 'environment'
    display_default = true
    fetch_virtual_env = true
    home_enabled = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'cyan'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'folder'


  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'red'
    background = 'transparent'
    template = ' {{ .HEAD }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '
