#!/usr/bin/env bash

pushd ~/personal/dev/env/.config/nvim
git add .
git commit -m 'autocommit to dev'
git push
popd

pushd ~/personal/dev/qmk
git add .
git commit -m 'autocommit to dev'
git push
popd

pushd ~/personal/dev
git add .
git commit -m 'autocommit to dev'
git push
popd
