#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed tldr fzf go base-devel sof-firmware brightnessctl fastfetch
sudo pacman -S --noconfirm --needed noto-fonts-emoji ttf-jetbrains-mono-nerd ttf-font-awesome noto-fonts-cjk 
