#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed tldr fzf go base-devel sof-firmware brightnessctl fastfetch less
sudo pacman -S --noconfirm --needed noto-fonts-emoji ttf-jetbrains-mono-nerd noto-fonts-cjk 
sudo pacman -S --noconfirm --needed man-db man-pages
