#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed nodejs npm
sudo pacman -S --noconfirm --needed typescript typescript-language-server svelte-language-server
npm install -g @fsouza/prettierd
#curl -fsSL https://deno.land/install.sh | sh
