#!/usr/bin/env bash

sudo pacman -S zsh
hash -r
sudo chsh -s $(which zsh)
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git $HOME/personal/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/personal/zsh-autosuggestions
